name: Github JS Test

on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Cache node modules
        id: cache-nodemodules
        uses: pat-s/always-upload-cache@v3.0.11
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-
      

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Prepare Job Status if success
        if: job.status == 'success'
        id: slack-prepare-success
        run: |
          echo "JOBSTATUS=success" >> $GITHUB_ENV
      - name: Fail intentionally  
        run: |
          exit 1
      - name: Prepare Job Status if failure
        if: failure()
        id: slack-prepare-failure
        run: |
          echo "JOBSTATUS2=failure" >> $GITHUB_ENV
      - name: Notify Dependencies
        if: always()
        run: pnpm testjs
        env:
          GHUB: ${{ env }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CI_CHANNEL }}
